version: "2"
linters:
  # enable:
  #   - gocognit
  settings:
    gocognit:
      min-complexity: 15
  # exclusions:
  #   rules:
  #     - path: _test\.go
  #       linters:
  #         - errcheck
    # paths:
    #   - _test\.go
