version: "2"
linters:
  enable:
    - containedctx
    - decorder
    - dupl
    - errcheck
    - errname
    - funcorder
    - gocognit
    - godoclint
    - godot
    - ineffassign
    - intrange
    - modernize
    - nestif
    - noctx
    - revive
    - testifylint
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - whitespace
  settings:
    gocognit:
      min-complexity: 15
    godoclint:
      default: all
