name: Lint and Uncloak Action

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
        description: The operating system to run the tests on
      go_version:
        required: true
        type: string
        description: The version of Go to use for the tests
      base_ref:
        required: true
        type: string
        description: The base Git reference to compare against (e.g. branch to merge into)
      head_ref:
        required: true
        type: string
        description: The head Git reference to compare against (e.g. branch containing changes)

jobs:
  linter:
    name: Run Linter
    uses: ./.github/workflows/lint-action.yml
    with:
      go_version: ${{ inputs.go_version }}
  test:
    name: Run Tests/Check Code Coverage
    needs: linter
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    uses: ./.github/workflows/uncloak-action.yml
    with:
      os: ${{ matrix.os }}
      go_version: ${{ inputs.go_version }}
      base_ref: ${{ inputs.base_ref }}
      head_ref: ${{ inputs.head_ref }}
