# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Run Linting and Tests

on:
  pull_request:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*" # Ignore all tags

jobs:
  lint-and-test:
    name: Run Linting and Tests
    uses: ./.github/workflows/lint-uncloak-action.yml
    with:
      go_version: 1.26.8
      base_ref: ${{ github.event.pull_request.base.sha || github.event.before }}
      head_ref: ${{ github.event.pull_request.head.sha || github.sha }}
