name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.8

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7
        with:
          # 'latest', 'nightly', or a semver
          version: "~> v2"
          args: release --clean --release-notes ${{ github.workspace }}/.github/latest_release_notes.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
