# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Run Linter and Tests

on:
  pull_request:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*" # Ignore all tags

# This is really only here due to being pretty rapid with updating Go releases.
env:
  GO_VERSION: 1.26.8

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
  test:
    needs: linter
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install latest version of uncloak
        run: |
          go install github.com/engmtcdrm/uncloak@latest
          echo "Installed $(uncloak --version)"

      - name: Run uncloak against '${{ github.BASE_REF }}'
        run: |
          git checkout ${{ github.BASE_REF }}
          git checkout ${{ github.HEAD_REF }}
          git branch -vv
          uncloak -t ${{ github.BASE_REF }} -d -v
