# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Run Linter and Tests

on:
  pull_request:
  push:
    branches:
      - "main"
    tags-ignore:
      - "*" # Ignore all tags

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.26.8

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.12
  test:
    needs: linter
    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
    uses: ./.github/workflows/uncloak-action.yml
    with:
      os: ${{ matrix.os }}
      go_version: 1.26.8
      base_ref: ${{ github.base_ref }}
      head_ref: ${{ github.head_ref }}
      # base_ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.ref_name }}
      # head_ref: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.ref || github.ref_name }}
